/** Monthly festival + general-knowledge poster catalog (10 posters). */
import demoVideoUrl from '../assets/Science_city_launch_video.mp4';

const GK_POSTERS = [
  {
    id: 'gk-hydration',
    kind: 'gk',
    badge: 'Health tip',
    headline: ['Stay', 'Hydrated', 'Daily'],
    scriptTop: 'Small Habits\nBig Results',
    expertLabel: 'A simple reminder on',
    focusTitle: 'Daily Hydration',
    pillars: 'Energy | Focus | Recovery',
    features: [
      ['Drink water', 'through the day'],
      ['Limit sugary', 'beverages'],
      ['Listen to', 'your body'],
    ],
    quote: 'Every sip supports a clearer, healthier day',
    scriptBottom: 'Steady Care\nStronger You',
    banner: 'SIMPLE HABITS  •  LASTING WELLNESS',
  },
  {
    id: 'gk-sleep',
    kind: 'gk',
    badge: 'Health tip',
    headline: ['Rest', 'Well', 'Tonight'],
    scriptTop: 'Quiet Nights\nBright Mornings',
    expertLabel: 'Guidance for',
    focusTitle: 'Healthy Sleep',
    pillars: 'Routine | Calm | Recovery',
    features: [
      ['Keep a', 'regular schedule'],
      ['Screen-free', 'before bed'],
      ['Create a', 'restful space'],
    ],
    quote: 'Good sleep is the foundation of everyday health',
    scriptBottom: 'Rest Deeply\nWake Ready',
    banner: 'BETTER SLEEP  •  BETTER DAYS',
  },
  {
    id: 'gk-nutrition',
    kind: 'gk',
    badge: 'Health tip',
    headline: ['Nourish', 'With', 'Care'],
    scriptTop: 'Balanced Plates\nHappy Bodies',
    expertLabel: 'A note on',
    focusTitle: 'Mindful Nutrition',
    pillars: 'Balance | Colour | Consistency',
    features: [
      ['Choose fresh', 'whole foods'],
      ['Eat colourful', 'meals'],
      ['Portion with', 'awareness'],
    ],
    quote: 'Food is fuel — choose what helps you thrive',
    scriptBottom: 'Eat Well\nFeel Well',
    banner: 'NOURISH TODAY  •  THRIVE TOMORROW',
  },
  {
    id: 'gk-movement',
    kind: 'gk',
    badge: 'Health tip',
    headline: ['Move', 'A Little', 'More'],
    scriptTop: 'Active Days\nStronger Years',
    expertLabel: 'Encouragement for',
    focusTitle: 'Daily Movement',
    pillars: 'Strength | Flexibility | Mood',
    features: [
      ['Walk for', '20 minutes'],
      ['Stretch your', 'body gently'],
      ['Make activity', 'enjoyable'],
    ],
    quote: 'Motion is medicine your body will thank you for',
    scriptBottom: 'Step Forward\nStay Strong',
    banner: 'MOVE DAILY  •  LIVE FULLY',
  },
  {
    id: 'gk-bp',
    kind: 'gk',
    template: 'risk-factor',
    badge: 'Health tip',
    headline: ['Know', 'Your', 'Numbers'],
    scriptTop: 'Awareness First\nCare Always',
    expertLabel: 'Insight on',
    focusTitle: 'Blood Pressure',
    pillars: 'Monitor | Manage | Maintain',
    features: [
      ['Check BP', 'regularly'],
      ['Reduce excess', 'salt intake'],
      ['Manage stress', 'calmly'],
    ],
    quote: 'Steady numbers start with steady daily care',
    scriptBottom: 'Stay Aware\nStay Steady',
    banner: 'AWARENESS  •  PREVENTION  •  CARE',
  },
  {
    id: 'gk-diabetes',
    kind: 'gk',
    badge: 'Health tip',
    headline: ['Balance', 'Your', 'Sugar'],
    scriptTop: 'Smart Choices\nSteady Levels',
    expertLabel: 'Support for',
    focusTitle: 'Blood Sugar Care',
    pillars: 'Diet | Activity | Monitoring',
    features: [
      ['Choose fibre', 'rich meals'],
      ['Walk after', 'eating'],
      ['Track levels', 'as advised'],
    ],
    quote: 'Balance grows from small, consistent choices',
    scriptBottom: 'Steady Levels\nSteady Life',
    banner: 'BALANCE TODAY  •  PROTECT TOMORROW',
  },
  {
    id: 'gk-heart',
    kind: 'gk',
    badge: 'Health tip',
    headline: ['Care', 'For Your', 'Heart'],
    scriptTop: 'Healthy Beats\nHappy Years',
    expertLabel: 'Advice on',
    focusTitle: 'Heart Wellness',
    pillars: 'Diet | Movement | Check-ups',
    features: [
      ['Eat heart', 'friendly foods'],
      ['Stay active', 'most days'],
      ['Never ignore', 'warning signs'],
    ],
    quote: 'A cared-for heart powers every moment you love',
    scriptBottom: 'Protect Your\nPrecious Beat',
    banner: 'HEART HEALTH  •  LIFE STRENGTH',
  },
  {
    id: 'gk-mental',
    kind: 'gk',
    badge: 'Health tip',
    headline: ['Mind', 'Matters', 'Too'],
    scriptTop: 'Breathe In\nLet Go',
    expertLabel: 'A reminder about',
    focusTitle: 'Mental Wellness',
    pillars: 'Rest | Talk | Support',
    features: [
      ['Pause and', 'breathe deeply'],
      ['Talk to', 'someone you trust'],
      ['Seek help', 'when needed'],
    ],
    quote: 'Caring for your mind is caring for your whole self',
    scriptBottom: 'Be Kind\nTo Your Mind',
    banner: 'MENTAL CARE  •  WHOLE HEALTH',
  },
  {
    id: 'gk-hygiene',
    kind: 'gk',
    badge: 'Health tip',
    headline: ['Clean', 'Hands', 'Save'],
    scriptTop: 'Prevention\nStarts Here',
    expertLabel: 'Basics of',
    focusTitle: 'Everyday Hygiene',
    pillars: 'Wash | Cover | Protect',
    features: [
      ['Wash hands', 'often'],
      ['Cover coughs', 'and sneezes'],
      ['Keep surfaces', 'clean'],
    ],
    quote: 'Prevention is the simplest form of protection',
    scriptBottom: 'Stay Clean\nStay Safe',
    banner: 'HYGIENE HABITS  •  HEALTHY HOMES',
  },
  {
    id: 'gk-checkup',
    kind: 'gk',
    badge: 'Health tip',
    headline: ['Book', 'Your', 'Check-up'],
    scriptTop: 'Prevention\nOver Cure',
    expertLabel: 'A nudge toward',
    focusTitle: 'Regular Check-ups',
    pillars: 'Screen | Detect | Protect',
    features: [
      ['Schedule yearly', 'visits'],
      ['Share full', 'health history'],
      ['Follow up on', 'results'],
    ],
    quote: 'Early care turns worry into confidence',
    scriptBottom: 'Check Early\nLive Easier',
    banner: 'PREVENT  •  DETECT  •  PROTECT',
  },
  {
    id: 'video-dummy',
    kind: 'video',
    badge: 'Video tip',
    headline: ['Health', 'Video', 'Demo'],
    focusTitle: 'Video content',
    videoUrl: demoVideoUrl,
  }
];

const FESTIVALS_BY_MONTH = {
  1: {
    id: 'fest-sankranti',
    kind: 'festival',
    festivalName: 'Makar Sankranti',
    badge: 'Festival greeting',
    headline: ['Warm', 'Wishes This', 'Sankranti'],
    scriptTop: 'Harvest Joy\nHealthy Starts',
    expertLabel: 'Celebrating',
    focusTitle: 'Makar Sankranti',
    pillars: 'Gratitude | Warmth | Wellness',
    features: [
      ['Share kindness', 'with family'],
      ['Enjoy festive', 'moments mindfully'],
      ['Begin the year', 'with healthy habits'],
    ],
    quote: 'May this Sankranti bring warmth, health, and new beginnings',
    scriptBottom: 'Festive Hearts\nHealthy Homes',
    banner: 'HAPPY MAKAR SANKRANTI  •  STAY WELL',
  },
  3: {
    id: 'fest-holi',
    kind: 'festival',
    festivalName: 'Holi',
    badge: 'Festival greeting',
    headline: ['Colours', 'Of Joy', '& Care'],
    scriptTop: 'Bright Colours\nBright Health',
    expertLabel: 'Celebrating',
    focusTitle: 'Happy Holi',
    pillars: 'Joy | Safety | Together',
    features: [
      ['Celebrate with', 'safe colours'],
      ['Stay hydrated', 'in the sun'],
      ['Care for skin', 'after festivities'],
    ],
    quote: 'May your Holi be colourful, joyful, and full of good health',
    scriptBottom: 'Play Safe\nCelebrate Well',
    banner: 'HAPPY HOLI  •  COLOURFUL WELLNESS',
  },
  8: {
    id: 'fest-independence',
    kind: 'festival',
    festivalName: 'Independence Day',
    badge: 'Festival greeting',
    headline: ['Proud', 'Healthy', 'India'],
    scriptTop: 'Freedom To\nLive Well',
    expertLabel: 'Honouring',
    focusTitle: 'Independence Day',
    pillars: 'Pride | Care | Community',
    features: [
      ['Celebrate with', 'responsibility'],
      ['Put health', 'first for family'],
      ['Build a stronger', 'healthier nation'],
    ],
    quote: 'True freedom includes the freedom to live healthy',
    scriptBottom: 'Proud Hearts\nHealthy Futures',
    banner: 'HAPPY INDEPENDENCE DAY  •  JAI HIND',
  },
  9: {
    id: 'fest-ganesh',
    kind: 'festival',
    festivalName: 'Ganesh Chaturthi',
    badge: 'Festival greeting',
    headline: ['Blessings', 'Of Health', '& Wisdom'],
    scriptTop: 'Ganpati Bappa\nMorya',
    expertLabel: 'Celebrating',
    focusTitle: 'Ganesh Chaturthi',
    pillars: 'Devotion | Wisdom | Wellness',
    features: [
      ['Begin with', 'gratitude'],
      ['Celebrate with', 'loved ones'],
      ['Choose eco-friendly', 'traditions'],
    ],
    quote: 'May Lord Ganesha bless your home with health and harmony',
    scriptBottom: 'Divine Blessings\nHealthy Living',
    banner: 'GANPATI BAPPA MORYA  •  STAY HEALTHY',
  },
  10: {
    id: 'fest-dussehra',
    kind: 'festival',
    festivalName: 'Dussehra',
    badge: 'Festival greeting',
    headline: ['Victory', 'Of Good', 'Health'],
    scriptTop: 'Good Over\nEvery Fear',
    expertLabel: 'Celebrating',
    focusTitle: 'Happy Dussehra',
    pillars: 'Courage | Care | Renewal',
    features: [
      ['Choose good', 'daily habits'],
      ['Protect family', 'wellness'],
      ['Start fresh with', 'healthy intent'],
    ],
    quote: 'May this Dussehra bring victory to your health and happiness',
    scriptBottom: 'Light Wins\nHealth Wins',
    banner: 'HAPPY DUSSEHRA  •  VICTORY TO WELLNESS',
  },
  11: {
    id: 'fest-diwali',
    kind: 'festival',
    festivalName: 'Diwali',
    badge: 'Festival greeting',
    headline: ['Lights', 'Of Health', '& Hope'],
    scriptTop: 'Diwali Glow\nHealthy Homes',
    expertLabel: 'Celebrating',
    focusTitle: 'Happy Diwali',
    pillars: 'Light | Love | Longevity',
    features: [
      ['Celebrate safely', 'with family'],
      ['Mind festive', 'sweets wisely'],
      ['Keep lungs safe', 'from smoke'],
    ],
    quote: 'May your Diwali sparkle with health, light, and togetherness',
    scriptBottom: 'Shine Bright\nStay Healthy',
    banner: 'HAPPY DIWALI  •  LIGHT UP WELLNESS',
  },
  12: {
    id: 'fest-christmas',
    kind: 'festival',
    festivalName: 'Christmas',
    badge: 'Festival greeting',
    headline: ['Warm', 'Wishes &', 'Wellness'],
    scriptTop: 'Season Of\nCare',
    expertLabel: 'Celebrating',
    focusTitle: 'Merry Christmas',
    pillars: 'Kindness | Comfort | Care',
    features: [
      ['Share warmth', 'with others'],
      ['Rest and', 'recharge'],
      ['Start the year', 'health-ready'],
    ],
    quote: 'May this Christmas fill your home with peace and good health',
    scriptBottom: 'Joyful Hearts\nHealthy Homes',
    banner: 'MERRY CHRISTMAS  •  HEALTHY NEW YEAR AHEAD',
  },
};

/**
 * Returns all posters for the given date.
 * Festival months: 1 festival greeting + all GK/Video posters.
 * Non-festival months: all GK/Video posters.
 */
export function getMonthlyPosters(date = new Date()) {
  const month = date.getMonth() + 1; // 1–12
  const festival = FESTIVALS_BY_MONTH[month] || null;
  const gk = GK_POSTERS.map((p) => ({ ...p }));

  if (festival) {
    return [festival, ...gk];
  }
  return gk;
}

export function getGeneralPosters() {
  return GK_POSTERS.map((p) => ({ ...p }));
}

export function getActiveFestival(date = new Date()) {
  return FESTIVALS_BY_MONTH[date.getMonth() + 1] || null;
}
